# Generated by Django 4.2.3 on 2023-07-15 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('datetime', models.DateTimeField(auto_created=True, verbose_name='Дата сдачи')),
                ('uid', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Имя опрашиваемого')),
                ('grade', models.PositiveSmallIntegerField(verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Пройденный тест',
                'verbose_name_plural': 'Пройденные тесты',
            },
        ),
        migrations.CreateModel(
            name='Test_levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Создание теста',
                'verbose_name_plural': 'Создание тестов',
            },
        ),
        migrations.CreateModel(
            name='Test_question_qty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_easy', models.PositiveSmallIntegerField(default=0, verbose_name='Количество "легких" вопросов')),
                ('qty_medium', models.PositiveSmallIntegerField(default=0, verbose_name='Количество "средних" вопросов')),
                ('qty_hard', models.PositiveSmallIntegerField(default=0, verbose_name='Количество "сложных" вопросов')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.test_levels', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Количество вопросов в категории',
                'verbose_name_plural': 'Количество вопросов в категориях',
            },
        ),
        migrations.CreateModel(
            name='Test_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('grade', models.PositiveSmallIntegerField(verbose_name='Оценка')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.test')),
            ],
            options={
                'verbose_name': 'Ответ на пройденный тест',
                'verbose_name_plural': 'Ответы на пройденные тесты',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='test_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.test_levels', verbose_name='Название теста'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_level', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=6, verbose_name='Сложность вопроса')),
                ('body', models.TextField(max_length=500, verbose_name='Вопрос')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
